### ISSUE TITLE
Exception during resolving reference's ID

### ISSUE THREAD

**Issue by dbojdo** [DXI-Ltd/doctrine-extension#3]
Doctrine\Common\Persistence\Mapping\MappingException: The class 'Dxi\DoctrineExtension\Reference\Mapping\Event\Adapter\ODM' was not found in the chain configured namespaces

symfony/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php:37
symfony/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/MappingDriverChain.php:112
symfony/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:151
symfony/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:332
symfony/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:78
symfony/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:216
symfony/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:281
symfony/vendor/dxi/doctrine-extension/src/Reference/Mapping/Event/Adapter/ODM.php:36
symfony/vendor/dxi/doctrine-extension/src/Reference/ReferencesListener.php:313
symfony/vendor/dxi/doctrine-extension/src/Reference/ReferencesListener.php:319
symfony/vendor/dxi/doctrine-extension/src/Reference/ReferencesListener.php:185
symfony/vendor/dxi/doctrine-extension/src/Reference/ReferencesListener.php:104
symfony/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php:63
symfony/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php:1040
symfony/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php:1863
symfony/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php:1827
symfony/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/DocumentManager.php:398

**Comment by dbojdo** [comment]
Problem caused by "null" identifier.

**Comment by chandon** [comment]
Thanks, that was quick (and with test unit) !
